src/api/urls.py
from django.urls import path

from .views import (
    car_list,
    car_detail,
    car_create,
    car_update,
    car_delete,
    car_comments_list,
    car_add_comment,
    obtain_auth_token,
)

urlpatterns = [
    path("token/", obtain_auth_token, name="api_token"),
    path("cars/", car_list, name="car_list"),
    path("cars/<int:pk>/", car_detail, name="car_detail"),
    path("cars/create/", car_create, name="car_create"),
    path("cars/<int:pk>/update/", car_update, name="car_update"),
    path("cars/<int:pk>/delete/", car_delete, name="car_delete"),
    path("cars/<int:pk>/comments/", car_comments_list, name="car_comments_list"),
    path("cars/<int:pk>/comments/add/", car_add_comment, name="car_add_comment"),
]

src/cars/urls.py
from django.urls import path

from . import views

app_name = "cars"

urlpatterns = [
    path("", views.index, name="index"),
    path("car/detail/<int:car_id>/", views.car_detail, name="car_detail"),
    path("car/create/", views.car_create, name="car_create"),
    path("car/update/<int:car_id>/", views.update_car, name="car_update"),
]

src/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("cars.urls", namespace="cars")),
    path("", include("comments.urls", namespace="comments")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cars/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import Base

User = get_user_model()


class Car(Base):
    make = models.CharField(verbose_name="Марка автомобиля", max_length=100)
    model = models.CharField(verbose_name="Модель автомобиля", max_length=100)
    year = models.PositiveIntegerField(verbose_name="Год выпуска")
    description = models.TextField(verbose_name="Описание")
    owner = models.ForeignKey(
        User, verbose_name="Владелец", on_delete=models.CASCADE, related_name="cars"
    )

    def __str__(self):
        return f"{self.make} {self.model} ({self.year})"

src/cars/forms.py
from django import forms

from .models import Car


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ("make", "model", "year", "description")

src/cars/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page

from core.loggers import apps_logger
from .forms import CarForm
from .services import (
    form_index_context,
    form_detail_context,
    create_car,
    get_car_and_check_owner,
)


@cache_page(10, key_prefix="index_page")
def index(request: HttpRequest) -> HttpResponse:
    """Главная страница."""
    context = form_index_context(request=request)
    apps_logger.debug("Контекст главной страницы получен")
    return render(request, "cars/index.html", context)


def car_detail(request: HttpRequest, car_id: int) -> HttpResponse:
    """Страница автомобиля полученного по id."""
    context = form_detail_context(request=request, car_id=car_id)
    apps_logger.debug(f"Контекст страницы автомобиля с id {car_id}")
    return render(request, "cars/car_detail.html", context)


@login_required
def car_create(request: HttpRequest) -> HttpResponse:
    """Форма создания автомобиля"""
    form = CarForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        create_car(form=form, user=request.user)
        apps_logger.debug(f"Пользователь с id {request.user.id} создал автомобиль")
        return redirect("cars:index")
    context = {"form": form}
    return render(request, "cars/create_car.html", context)


@login_required
def update_car(request: HttpRequest, car_id: int) -> HttpResponse:
    """Форма обновления автомобиля."""
    car = get_car_and_check_owner(request=request, car_id=car_id)

    if request.method == "POST":
        form = CarForm(request.POST, instance=car)
        if form.is_valid():
            form.save()
            apps_logger.debug(
                f"Пользователь с id {request.user.id} обновил автомобиль {car_id}."
            )
            return redirect("cars:car_detail", car_id=car.id)
    else:
        form = CarForm(instance=car)

    context = {
        "form": form,
        "car": car,
    }
    return render(request, "cars/update_car.html", context)

src/templates/cars/car_detail.html
{% extends 'base.html' %}
{%block title%}{{ car.model|truncatechars:30 }}{% endblock %}
{% block content %}
<main class="d-flex justify-content-center align-items-center vh-100">
    <div class="row w-100" style="max-width: 800px;">
        <aside class="col-12 col-md-3 mb-3">
            <ul class="list-group list-group-flush">
                <li>
                    Марка автомобиля: {{ car.make }}
                </li>
                <li>
                    Модель: {{ car.model }}
                </li>
                <li>
                    Год выпуска: {{ car.year }}
                </li>
                <li>
                    Описание: {{ car.description }}
                </li>
            </ul>
        </aside>
        {% if car.owner.id == request.user.id %}
            <a class="btn btn-primary mb-3" href="{% url 'cars:car_update' car.id %}">Обновить</a>
        {% endif %}
        <article class="col-12 col-md-9">
            {% include 'includes/comments.html' %}
        </article>
    </div>
</main>
{% endblock %}

src/templates/cars/create_car.html
{% extends 'base.html' %}
{%block title%}Новый автомобиль{% endblock %}
{% block content %}
<main>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Создать автомобиль на сайте
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group row my-3 p-3">
                                <label for="id_text">
                                    Марка Автомобиля
                                    <span class="required text-danger">*</span>
                                </label>
                                {{form.make}}
                                <small id="id_text-help" class="form-text text-muted">
                                    Введите марку автомобиля
                                </small>
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_group">
                                    Модель
                                </label>
                                {{form.model}}
                                <small id="id_group-help" class="form-text text-muted">
                                    Введите модель автомобиля
                                </small>
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_year">
                                    Год выпуска автомобиля
                                </label>
                                {{form.year}}
                                <small id="id_year-help" class="form-text text-muted">
                                    Введите год выпуска автомобиля
                                </small>
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_description">
                                    Описание
                                </label>
                                {{form.description}}
                                <small id="id_description-help" class="form-text text-muted">
                                    Введите описание автомобиля
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    {% if is_edit %}
                                    Добавить пост
                                    {% else %}
                                    Сохранить изменения
                                    {% endif %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

src/templates/cars/index.html
{% extends 'base.html' %}
{% block title %}Автомобили{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Список доступных автомобилей</h1>
    {% for car in page_obj %}
    {% include 'includes/one_car.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'cars/includes/paginator.html' %}
  </div>
{% endblock %}

src/templates/cars/update_car.html
{% extends 'base.html' %}
{% block title %}Редактировать автомобиль{% endblock %}
{% block content %}
<main>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">
                        Редактировать автомобиль
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group row my-3 p-3">
                                <label for="id_make">
                                    Марка автомобиля
                                    <span class="required text-danger">*</span>
                                </label>
                                {{ form.make }}
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_model">
                                    Модель автомобиля
                                    <span class="required text-danger">*</span>
                                </label>
                                {{ form.model }}
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_year">
                                    Год выпуска
                                </label>
                                {{ form.year }}
                            </div>
                            <div class="form-group row my-3 p-3">
                                <label for="id_description">
                                    Описание
                                </label>
                                {{ form.description }}
                            </div>
                            <div class="d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary">
                                    Сохранить изменения
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}