src/api/urls.py
from django.urls import path

from .views import (
    car_list,
    car_detail,
    car_create,
    car_update,
    car_delete,
    car_comments_list,
    car_add_comment,
    obtain_auth_token,
)

urlpatterns = [
    path("token/", obtain_auth_token, name="api_token"),
    path("cars/", car_list, name="car_list"),
    path("cars/<int:pk>/", car_detail, name="car_detail"),
    path("cars/create/", car_create, name="car_create"),
    path("cars/<int:pk>/update/", car_update, name="car_update"),
    path("cars/<int:pk>/delete/", car_delete, name="car_delete"),
    path("cars/<int:pk>/comments/", car_comments_list, name="car_comments_list"),
    path("cars/<int:pk>/comments/add/", car_add_comment, name="car_add_comment"),
]

src/cars/urls.py
from django.urls import path

from . import views

app_name = "cars"

urlpatterns = [
    path("", views.index, name="index"),
    path("car/detail/<int:car_id>/", views.car_detail, name="car_detail"),
    path("car/create/", views.car_create, name="car_create"),
    path("car/update/<int:car_id>/", views.update_car, name="car_update"),
]

src/comments/urls.py
from django.urls import path

from . import views

app_name = "comments"

urlpatterns = [
    path("comment/create/<int:car_id>/", views.add_comment, name="add_comment"),
]

src/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("cars.urls", namespace="cars")),
    path("", include("comments.urls", namespace="comments")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comments/models.py
from django.db import models

from cars.models import Car, User
from core.models import Base


class Comment(Base):
    content = models.TextField(verbose_name="Тело комментария")
    car = models.ForeignKey(
        Car,
        verbose_name="Автомобиль к которому относится комментарий",
        on_delete=models.CASCADE,
        related_name="comment_car",
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор комментария",
        on_delete=models.CASCADE,
        related_name="comment_author",
    )

    def __str__(self):
        return f"Comment by {self.author} on {self.car}"

src/comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

src/comments/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect

from cars.services import get_car_by_id
from core.loggers import apps_logger
from .forms import CommentForm
from .services import create_comment


@login_required
def add_comment(request, car_id: int):
    """Форма создания комментария."""
    car = get_car_by_id(car_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        apps_logger.debug(
            f"Пользователь с id {request.user.id} создал комментарий к автомобилю {car_id}."
        )
        create_comment(user=request.user, form=form, car=car)
    return redirect("cars:car_detail", car_id=car_id)

src/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
        <form method="post" action="{% url 'comments:add_comment' car.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
                {{ form.content|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
</div>
{% endif %}

{% for comment in comments %}
<div class="media mb-4">
    <div class="media-body">
        <p>
            {{ comment.author.username }} - {{ comment.content }}
        </p>
    </div>
</div>
{% endfor %}

src/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} </p>
</footer>

src/templates/includes/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

src/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: white">
    <div class="container">
        <a href="{% url 'cars:index' %}">
            <span style="color:red">Главная</span>
        </a>
        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'cars:car_create' %}active{% endif %}"
                   href="{% url 'cars:car_create' %}">Зарегистрировать новую машину</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}"
                   href="{% url 'users:password_change' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
                   href="{% url 'users:logout' %}">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
                   href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
                   href="{% url 'users:signup' %}">Регистрация</a>
            </li>
            {% endif %}
        </ul>
        {% endwith %}
    </div>
</nav>

src/templates/includes/one_car.html
<ul>
  <li>
    Марка автомобиля: {{car.make}}
  </li>
  <li>
    Модель: {{car.model}}
  </li>
  <li>
    Год выпуска: {{car.year}}
  </li>
  <li>
    Описание: {{car.description}}
  </li>
</ul>
<p>{{ post.text }}</p>
<a href="{% url 'cars:car_detail' car.id %}">Подробная информация </a>
<br>